### PR TITLE
Small panel refactors

### PR DESCRIPTION
**Pull request by mark-koch**
Some small improvements following on from #31
* Better `ToolbarSection` constructor
* Turn commands into dataclasses

### CODE REVIEW

**Comment by jvdwetering** [comment]
What does changing these commands into dataclasses do?

**Comment by mark-koch** [comment]
Dataclasses give us `__eq__` for free. Normally, they also generate `__init__` but there was an issue with the `QUndoCommand` base class.

But I figured out how to make it work (see latest commit), so now we don't have to write constructors for commands

**Comment by jvdwetering** [comment]
Okay, is this fine for merging now?

**Comment by mark-koch** [comment]
Yes, should be good to go 👍

**Pull request merged**
