### PR TITLE
Make `string_to_phase` slighty more robust.

### PR DESCRIPTION
**Pull request by dlyongemallo**
Add a test for various input formats which are expected to result in a `Fraction`.

See issue #148.

### CODE REVIEW

**Comment by boldar99** [comment]
We could add a couple of tests for the complex case. The rest seems good!

**Comment by dlyongemallo** [comment]
I've added a basic test for the complex input case, but there's something I'm not sure about. When the `fraction_or_complex` argument has the value `complex` and `str` contains variable parameters, e.g., `a + bj`, what the intended result? Is the `Poly` case with variable parameters intended to be used only for a `fraction` input (and thus an error should be shown if a `complex` input is given with variable parameters), or is the intention to treat `j` as the imaginary unit in the `complex` case?

**Comment by jvdwetering** [comment]
I don't think we have really thought about variables in the complex case. So I think for now not allowing users to do this would be the way to go.

**Comment by dlyongemallo** [comment]
Okay, I've refactored the code to disallow variables for complex inputs. I've also split the fraction and complex input logic into separate functions so it's clear what's allowed for each.

**Comment by jvdwetering** [comment]
Is this ready to be merged?

**Comment by dlyongemallo** [comment]
Yes, ready to be merged.

**Pull request merged**
