### PR TITLE
Rule editor UI

### LINKED ISSUE #83: UI for creating custom rewrites
ZXLive supports adding custom rewrites. To do so, we can choose a graph file for the left and the right-hand side of the equality. It would be a better experience to have a window for creating custom rewrites. This window should be split vertically, where the user can draw the left and the right-hand side of the rewrite.

### PR DESCRIPTION
**Pull request by RazinShaikh**
Closes #83

### CODE REVIEW

**Comment by jvdwetering** [comment]
Looks good! Something that's a little confusing: When you have the rule editor open, you can still save a graph. But I think what this does is just save the currently selected graph. I would have expected this to save the whole rule as a lemma to a file. Currently all the rules are stored in a single file, but if we want users to be able to share lemmas between each other, we probably want each rule to be in a separate file. So maybe instead of having`customrules.json`, there could be a designated folder which holds all the lemmas?
So maybe we want some logic to determine what the type of thing is that we are saving, a graph or a rule.
Anyway, this is all not so important for this PR.

**Comment by jvdwetering** [comment]
If you click on 'Save rule' while the diagram is not well-formed, for instance if it has a boundary node not connected to anything, then it throws an exception instead of telling the user the diagram is not well-formed.
It also allows you to save rules which are not well-typed, that have for instance a different amount of boundaries on the LHS then on the RHS. If you do this and match the LHS, it simply doesn't match which is weird behaviour. It probably would be best to just pop up a message saying that the rule is not well-typed.

**Comment by jvdwetering** [comment]
Also maybe something not for this PR: Have a button that allows the user to switch the LHS and RHS. Or maybe something that allows you to automatically create the reverse rule?

**Comment by RazinShaikh** [comment]
> Also maybe something not for this PR: Have a button that allows the user to switch the LHS and RHS. Or maybe something that allows you to automatically create the reverse rule?

@boldar99 is working on the side panel for rewrite rules (#71). We can have a button there to apply the rewrite rule in the forward or backward direction.

**Comment by RazinShaikh** [comment]
@jvdwetering the rules are now saved to individual files and the save button in the file menu has the right behavior. I have also added a function to check the rule and warn the user.

**Pull request merged**
