### PR TITLE
Move UI code for showing errors out of `custom_rule.py`.

### PR DESCRIPTION
**Pull request by dlyongemallo**
Incidentally, make the warning dialogs modal (see issue #156).

### CODE REVIEW

**Comment by dlyongemallo** [comment]
Two further questions:
* `check_rule` returns a `bool`, but this is never used. Is this return value necessary?
* `check_rule` is always called with `show_error = True`. Is this parameter necessary?

**Comment by jvdwetering** [comment]
I think the bool was originally intended to check if the operation succeeded. But since with this commit it instead raises an Exception, that no longer makes sense. Also with this behaviour, supressing the exceptions with show_error also makes less sense so that that parameter can be removed.

**Comment by dlyongemallo** [comment]
Okay, I've removed both the parameter and the return value.

**Comment by hm919** [comment]
Has this fixed issue #156 ?

**Comment by dlyongemallo** [comment]
The specific issue of `show_error_msg` not taking a parent has been fixed. It looks to me like all dialog functions defined in `dialogs.py` take a parent now. The aside about the API being inconsistent is still true, but that's mostly a cosmetic matter and I think we can close issue #156 now (or leave it open and rename it to "make dialogs more API consistent" or something like that).

**Pull request merged**
