### PR TITLE
Add framework for testing using pytest-qt. Also add a few simple tests.

### PR DESCRIPTION
**Pull request by dlyongemallo**

### CODE REVIEW

**Comment by RazinShaikh** [comment]
Can you please resolve the merge conflicts?

**Comment by RazinShaikh** [comment]
Also, do you know how to run these tests automatically after every commit? @boldar99 was looking at setting up something like that in the deploy branch https://github.com/Quantomatic/zxlive/pull/96

**Review by RazinShaikh — APPROVED** [review]
Looks good

**Comment by dlyongemallo** [comment]
> Also, do you know how to run these tests automatically after every commit? @boldar99 was looking at setting up something like that in the deploy branch #96

Just filed #137 for this before I saw your question. 

The instructions are [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks). Since it's already set up for the pyzx repro, whoever set it up there (I assume @jvdwetering?) should be able to just do something similar for this repo.

**Pull request merged**
